name: air101

on:
  push:
    paths:
      - '.github/workflows/air101.yml'
      - 'lua/**'
      - 'luat/**'
      - 'components/**'
      - 'bsp/air101/**'
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook-101-action

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: prepare software
      run: |
        sudo apt-get update
        sudo apt-get install git gcc-multilib libc6 libgcc1 libstdc++5 libstdc++6 libsdl-dev p7zip-full -y
        sudo apt-get install libncurses5-dev -y
        sudo add-apt-repository ppa:xmake-io/xmake -y
        sudo apt update
        sudo apt install xmake
    - name: clone 101
      run: |
        sudo sh -c "curl https://raw.githubusercontent.com/kadwanev/retry/master/retry -o /usr/local/bin/retry && chmod +x /usr/local/bin/retry"
        cd ..
        retry 'git clone --branch=master https://gitee.com/openLuat/luatos-soc-air101 air101'
    - name: make
      run: |
        cd ../air101
        gcc -o tools/xt804/wm_tool tools/xt804/wm_tool.c -pthread
        chmod +x tools/xt804/wm_tool
        mkdir /home/runner/toolchains
        wget -q https://github.com/openLuat/LuatOS/releases/download/v0.0.1/csky-elfabiv2-tools-x86_64-minilibc-20210423.tar.gz -O /home/runner/toolchains/csky-elfabiv2-tools-x86_64-minilibc-20210423.tar.gz
        xmake g --pkg_searchdirs=/home/runner/toolchains
        xmake -y
        mkdir ../LuatOS/luatosfw
        mv build/out/*.soc ../LuatOS/luatosfw
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: air101
        path: luatosfw
    - name: report if failure
      if: always()
      env:
        STATUS: ${{ job.status }}
        MQTTADDR: ${{ secrets.MQTTADDR }}
        MQTTPORT: ${{ secrets.MQTTPORT }}
        MQTTTOPIC: ${{ secrets.MQTTTOPIC }}
        DD_APPKEY: ${{ secrets.DD_APPKEY }}
        DD_APPSECRET: ${{ secrets.DD_APPSECRET }}
        DD_NOTIFY_LIST: ${{ secrets.DD_NOTIFY_LIST }}
        DD_API_TOKEN: ${{ secrets.DD_API_TOKEN }}
        DD_API_SEND: ${{ secrets.DD_API_SEND }}
      run: |
        sudo pip3 install paho_mqtt gitpython requests
        cd tools
        if [ "$STATUS" = "failure" ];then python3 ciNotify.py $MQTTADDR $MQTTPORT $MQTTTOPIC "https://github.com/openLuat/LuatOS/actions/runs/$GITHUB_RUN_ID" "air101" "$DD_APPKEY" "$DD_APPSECRET" "$DD_NOTIFY_LIST" "$DD_API_TOKEN" "$DD_API_SEND"; fi
